### ISSUE TITLE
how about melgan using lvc

### ISSUE THREAD

**Issue by hdmjdp** [JackZiLong/LVCNet#1]
In MELGAN, there is not input noise as x. So

**Comment by zceng** [comment]
Thanks for your attention to our research. 
Due to the absence of input noise, the LVCNet cannot directly be applied in MELGAN. However, We can refer to the step-by-step upsampling network structure of MELGAN to design a similar and novel network. On the other hand, the input noise can be replace by the mel-spectrum, which is also use to as the condition input.
LVCNet does not limit the format of input data, and just provides a design idea of network for waveform generation.

**Comment by hdmjdp** [comment]
@ZENGZHEN-TTS Thanks for replying. This means only we insert the lvc-block in resblock which is after upsample module?

**Comment by zceng** [comment]
Yes. Notice that the mel-spectrum need be used as the condition input. 
In addition, due to other things, we haven't test the effect of LVCNet on MELGAN. But I believe you can try it!

**Comment by hdmjdp** [comment]
@ZENGZHEN-TTS But my hop_size=600, lvc_layers_each_block cannot be 10.

**Comment by zceng** [comment]
`lvc_layers_each_block`  is related to the receptive field, and it is not matter if it bigger.
